### ISSUE TITLE
§303 Player Fluidity Act

### ISSUE THREAD

**Issue by rmartinho** [LoungeCPP/Nomic#11]
Since there's only three of us, I want to enact rules to allow players to join.

> At any point new players can join the game by making public their desire to join. These rules apply to all players from the moment they join the game. When a player joins the game, their first turn takes place in the turn order established by the rules that are in effect after completion of the circuit of turns that was current at the time of joining.

This means anyone can join. I took care to make sure this doesn't interfere with turn order in annoying ways:

 - if your second turn was coming up after this, you don't get anyone sneaking in by joining at the right moment;
 - there's no need to track special turn orders for new players; their turns just get scheduled according to the rules we have currently.

E.g. we have A, B, D, playing, turn order is alphabetical. It's B's turn, and the next turns will be D, A, B, D, .... If C joins now, the next turns will be D, A, B, C, D, ....

**Comment by shoooe** [comment]
Looks good to me.

**Comment by thecoshman** [comment]
I don't think this is worded as well at can be. The main sticking point for me is "after complete of the circuit of turns that was current at the time of joining", to me, that doesn't match up with your example. That wording would imply to me, if you have players "A, B, C" we are taking players C first turn, we are in the "first circuit" of turns, as such if player D want's to join, they would actually go right after player C. I believe the 'correct' behaviour would be that as it is players D turn, both player A and B should get to take a turn before player D.

That said, I don't want the third turn in a row to be rejected simply because it is not perfect. I think that happened for both me and jeff, and it's not as fun simply rejecting everything all the time.
